"use server";
import { revalidatePath } from "next/cache";
import type { PartnerChallenge } from "@prisma/client";
import { db } from "@/lib/db";
import { requireAdminSession } from "@/features/auth/admin-auth";
import { parseVietnamDatetimeLocal } from "@/features/partner-os";
import { getVietnamMonthRange, getVietnamWeekRange, getValidPartnerOrdersForRange } from "@/features/leaderboards";
import { createAdminNotification } from "@/features/notifications";

function period(ch: { periodType: string; startAt: Date | null; endAt: Date | null }, approval?: Date) { const now = new Date(); if (ch.periodType === "weekly") return { ...getVietnamWeekRange(now), key: "week" }; if (ch.periodType === "lifetime") return { start: new Date(0), end: now, key: "lifetime" }; if (ch.periodType === "fixed_window") return { start: ch.startAt ?? new Date(0), end: ch.endAt ?? now, key: ch.startAt?.toISOString().slice(0,10) ?? "fixed_window" }; if (ch.periodType === "after_approval") return { start: approval ?? new Date(0), end: new Date((approval ?? now).getTime() + 30*86400000), key: "after_approval" }; const m = getVietnamMonthRange(now); return { ...m, key: new Intl.DateTimeFormat("en-CA", { year:"numeric", month:"2-digit", timeZone:"Asia/Ho_Chi_Minh" }).format(now) }; }

export async function calculateChallengeProgress(challenge: PartnerChallenge, partnerId: string, approval?: Date) { const p = period(challenge, approval); const orders = (await getValidPartnerOrdersForRange("referral_ctv", p.start, p.end)).filter(o => o.partnerId === partnerId); let value = challenge.targetMetric === "valid_revenue" ? orders.reduce((s,o)=>s+o.eligibleProductRevenue,0) : orders.length; if (challenge.challengeType === "first_order_after_approval" && approval) { value = orders.some(o => o.createdAt <= new Date(approval.getTime()+72*3600000)) ? 1 : 0; } return { periodKey: p.key, currentValue: value, targetValue: challenge.targetValue, status: value >= challenge.targetValue ? "completed" : (challenge.endAt && challenge.endAt < new Date() ? "expired" : "in_progress"), completedAt: value >= challenge.targetValue ? new Date() : null }; }

export async function getPartnerChallenges(partnerId: string) { const partner = await db.partner.findUniqueOrThrow({ where: { id: partnerId } }); const challenges = await db.partnerChallenge.findMany({ where: { status: "active" }, orderBy: [{ priority: "desc" }, { createdAt: "desc" }] }); return Promise.all(challenges.map(async (c) => ({ challenge: c, progress: await calculateChallengeProgress(c, partnerId, partner.createdAt) }))); }
function str(fd: FormData,k:string){return String(fd.get(k)??"").trim()}
function int(fd: FormData,k:string){const n=Number(str(fd,k)); return Number.isFinite(n)?Math.max(0,Math.floor(n)):0}
export async function createChallengeAction(fd: FormData) { await requireAdminSession(); await db.partnerChallenge.create({ data: { title: str(fd,"title"), description: str(fd,"description") || null, challengeType: str(fd,"challengeType") || "monthly_orders", targetMetric: str(fd,"targetMetric") || "valid_order_count", targetValue: int(fd,"targetValue"), periodType: str(fd,"periodType") || "monthly", startAt: parseVietnamDatetimeLocal(fd.get("startAt")) ?? null, endAt: parseVietnamDatetimeLocal(fd.get("endAt")) ?? null, rewardType: int(fd,"rewardAmount") ? "bonus_amount" : "manual", rewardAmount: int(fd,"rewardAmount") || null, rewardDescription: str(fd,"rewardDescription") || null, status: str(fd,"status") || "draft", priority: int(fd,"priority") } }); revalidatePath("/admin/challenges"); revalidatePath("/dashboard/thu-thach"); }
export async function archiveChallengeAction(fd: FormData) { await requireAdminSession(); await db.partnerChallenge.update({ where: { id: str(fd,"id") }, data: { status: "archived" } }); revalidatePath("/admin/challenges"); }
export async function recalculateChallengesAction() { await requireAdminSession(); const partners = await db.partner.findMany({ where: { partnerType: { code: "referral_ctv" }, status: "approved" } }); const challenges = await db.partnerChallenge.findMany({ where: { status: "active" } }); for (const p of partners) for (const c of challenges) { const prog = await calculateChallengeProgress(c,p.id,p.createdAt); await db.partnerChallengeProgress.upsert({ where: { challengeId_partnerId_periodKey: { challengeId: c.id, partnerId: p.id, periodKey: prog.periodKey } }, update: prog, create: { challengeId: c.id, partnerId: p.id, ...prog } }); if (prog.status === "completed") await createAdminNotification({ type:"challenge.completed", title:"CTV hoàn thành thử thách cần xét thưởng", actionUrl:"/admin/challenges", entityType:"PartnerChallenge", entityId:c.id, severity:"warning" }); } revalidatePath("/admin/challenges"); revalidatePath("/dashboard/thu-thach"); }
