import { DashboardShell } from "@/components/layout/dashboard-shell";
import { requirePartnerSession } from "@/features/auth/partner-auth";
import { getEmergingLeaderboard, getLeaderboard, getVietnamMonthRange, getVietnamWeekRange, type LeaderboardMetric } from "@/features/leaderboards";
import { formatVnd } from "@/lib/money";
export const dynamic="force-dynamic";
type TabKey="week_revenue"|"week_orders"|"month_revenue"|"month_orders"|"emerging";
const tabs:Record<TabKey,{title:string;range:"week"|"month"|"emerging";metric:LeaderboardMetric}>={week_revenue:{title:"Top doanh thu tuần",range:"week",metric:"revenue"},week_orders:{title:"Top số đơn tuần",range:"week",metric:"orders"},month_revenue:{title:"Top doanh thu tháng",range:"month",metric:"revenue"},month_orders:{title:"Top số đơn tháng",range:"month",metric:"orders"},emerging:{title:"CTV mới nổi",range:"emerging",metric:"orders"}};
function isTabKey(v?:string):v is TabKey{return Boolean(v&&v in tabs)}
export default async function Page({searchParams}:{searchParams:Promise<{tab?:string}>}){const sp=await searchParams;const session=await requirePartnerSession();const key=isTabKey(sp.tab)?sp.tab:"week_revenue";const tab=tabs[key];const range=tab.range==="month"?getVietnamMonthRange():getVietnamWeekRange();const board=tab.range==="emerging"?await getEmergingLeaderboard(session.account.partner.id):await getLeaderboard(tab.metric,range,"referral_ctv",10,session.account.partner.id);const rows=board.rows;const currentOutside=board.current && !rows.some(r=>r.partnerId===board.current!.partnerId) ? board.current : undefined;return <DashboardShell><div className="space-y-6"><div><h1 className="text-3xl font-bold text-merly-900">Bảng xếp hạng</h1><p className="mt-2 text-stone-600">Xếp hạng dựa trên đơn hàng hợp lệ. Đơn hủy, hoàn, khách không nhận hoặc đơn không đúng chính sách sẽ không được tính.</p></div><div className="flex flex-wrap gap-2">{(Object.keys(tabs) as TabKey[]).map(k=><a className={`rounded-full px-4 py-2 text-sm font-semibold ${k===key?"bg-merly-700 text-white":"bg-white text-merly-700"}`} href={`/dashboard/bang-xep-hang?tab=${k}`} key={k}>{tabs[k].title}</a>)}</div><div className="card overflow-x-auto"><h2 className="text-xl font-bold text-merly-900">{tab.title}</h2><p className="text-sm text-stone-500">Khung thời gian: {tab.range==="emerging"?"CTV được duyệt trong 30 ngày gần đây":range.label}</p><table className="mt-4 min-w-full text-left text-sm"><thead className="text-stone-500"><tr><th>Hạng</th><th>CTV</th><th>Số đơn hợp lệ</th><th>Doanh thu hợp lệ</th><th>Hoa hồng tạm tính</th></tr></thead><tbody>{rows.map(r=><tr key={r.partnerId} className={`border-t border-stone-100 ${r.partnerId===session.account.partner.id?"bg-rose-50 font-semibold":""}`}><td className="py-3">#{r.rank}</td><td>{r.displayName}</td><td>{r.orderCount}</td><td>{formatVnd(r.revenue)}</td><td>{formatVnd(r.commission)}</td></tr>)}{currentOutside?<tr className="border-t border-rose-200 bg-rose-50 font-semibold"><td className="py-3">#{currentOutside.rank}</td><td>{currentOutside.displayName} (chị)</td><td>{currentOutside.orderCount}</td><td>{formatVnd(currentOutside.revenue)}</td><td>{formatVnd(currentOutside.commission)}</td></tr>:null}{!rows.length?<tr><td colSpan={5} className="py-6 text-stone-500">Chưa có dữ liệu xếp hạng hợp lệ.</td></tr>:null}</tbody></table></div></div></DashboardShell>}
