import { Prisma } from "@prisma/client";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { CopyButton } from "@/features/growth/copy-button";
import { shortUrl } from "@/features/growth/utils";
import { requirePartnerSession } from "@/features/auth/partner-auth";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<{ product?: string; message?: string }> }) {
  const session = await requirePartnerSession();
  const partner = session.account.partner;
  const { product = "", message } = await searchParams;
  const links = await db.shortLink.findMany({ where: { partnerId: partner.id }, orderBy: { createdAt: "desc" }, include: { _count: { select: { clicks: true } } } });
  const productWhere: Prisma.HaravanProductWhereInput = product ? { OR: [{ title: { contains: product, mode: "insensitive" } }, { handle: { contains: product, mode: "insensitive" } }, { variants: { some: { sku: { contains: product, mode: "insensitive" } } } }] } : {};
  const products = await db.haravanProduct.findMany({ where: productWhere, orderBy: { syncedAt: "desc" }, take: product ? 10 : 5 });
  return <DashboardShell><div className="card space-y-5"><h1 className="text-3xl font-bold text-merly-900">Link rút gọn CTV Merly</h1><p className="text-stone-600">Chỉ dùng URL merlyshoes.com. Hệ thống tự thêm mã khách hàng <b>ref</b> của chị; link tuyển partner dùng <b>partner_ref</b> riêng.</p>{message ? <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{decodeURIComponent(message)}</p> : null}<form method="post" action="/dashboard/link-rut-gon/create" className="flex flex-col gap-3 md:flex-row"><input required name="destinationUrl" className="flex-1 rounded-xl border p-3" placeholder="https://merlyshoes.com/products/..." /><button className="btn-primary">Tạo link</button></form><div className="rounded-2xl border border-rose-100 p-4"><h2 className="font-bold text-merly-900">Chọn nhanh sản phẩm Haravan</h2><form className="mt-3 flex gap-2"><input className="input flex-1" name="product" defaultValue={product} placeholder="Tìm tên, handle, SKU"/><button className="btn-secondary">Tìm sản phẩm</button></form><div className="mt-4 grid gap-2">{products.map((p)=><form key={p.id} method="post" action="/dashboard/link-rut-gon/create" className="flex flex-wrap items-center gap-3 rounded-xl bg-rose-50 p-3"><input type="hidden" name="destinationUrl" value={p.productUrl ?? ""}/>{p.imageUrl ? <div aria-label={p.title} role="img" className="h-12 w-12 rounded-lg bg-cover bg-center" style={{ backgroundImage: `url(${p.imageUrl})` }}/> : null}<span className="flex-1"><b>{p.title}</b><span className="block text-xs text-stone-500">{p.handle}</span></span><button className="btn-primary" disabled={!p.productUrl}>Tạo short link</button>{p.productUrl ? <CopyButton value={p.productUrl}/> : null}</form>)}{products.length===0?<p className="text-sm text-stone-500">Chưa có sản phẩm phù hợp. Chị vẫn có thể dán URL thủ công.</p>:null}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-stone-500"><tr><th>Short URL</th><th>URL đích</th><th>Clicks</th><th>Ngày tạo</th><th>Trạng thái</th><th /></tr></thead><tbody>{links.map((link) => { const url = shortUrl(link.slug); return <tr className="border-t border-rose-50" key={link.id}><td className="py-3 font-mono">{url}</td><td className="max-w-sm truncate">{link.destinationUrl}</td><td>{link._count.clicks}</td><td>{link.createdAt.toLocaleDateString("vi-VN")}</td><td>{link.disabledAt ? "Đã tắt" : "Đang bật"}</td><td><CopyButton value={url} /></td></tr>; })}</tbody></table></div></div></DashboardShell>;
}
